language: generic

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          # Use nvm to install and use the Node LTS version (nvm is installed on all Travis images)
          # - nvm install lts/*
          - npm install @semantic-release/changelog -D
          - npx semantic-release
